### ISSUE TITLE
question in grid_world.py

### ISSUE THREAD

**Issue by amiltonwong** [lazyprogrammer/machine_learning_examples#10]
Hi, @lazyprogrammer ,

Does it miss a line "(1, 1): step_cost," under line [104](https://github.com/lazyprogrammer/machine_learning_examples/blob/master/rl/grid_world.py#L104) in grid_world.py, according to only two terminal states such as (0, 3) and (1, 3)?

**Comment by lazyprogrammer** [comment]
I guess you'd have to take the course to know this, but (1, 1) is actually a wall

**Comment by amiltonwong** [comment]
thansks
