### ISSUE TITLE
Suggest me the example which is suitable for my requirement and source of the file : mymodel.pkl.

### ISSUE THREAD

**Issue by babukalamgi** [lazyprogrammer/machine_learning_examples#16]
Hi,

Greetings,

I have jobs data, I want to get the matching results when I enter some keywords in a search text box.
like, google text box.

As of now, I am working with supervised_class/ if working with right example,
from where I can download mymodel.pkl file. 

Thanks,
Babu Kalamgi

**Comment by lazyprogrammer** [comment]
You're supposed to make it yourself by running the training script
