### ISSUE TITLE
seem took the wrong column as Y?

### ISSUE THREAD

**Issue by cyrusonline** [lazyprogrammer/machine_learning_examples#20]
https://github.com/lazyprogrammer/machine_learning_examples/blob/master/ann_logistic_extra/process.py

Y = data[:,-1].astype(np.int32)
is that should be taking the first column rather than the last column as Y?
as the last column is not binary data (0 or 1)?

**Comment by lazyprogrammer** [comment]
Post your course-related questions on the course Q&A
