### ISSUE TITLE
nb.py line 24 , column 48 is referenced as the score but it looks like column 58 should be

### ISSUE THREAD

**Issue by jtmhom88** [lazyprogrammer/machine_learning_examples#27]
https://github.com/lazyprogrammer/machine_learning_examples/blob/master/nlp_class/nb.py
Looks like column 58 has the 0,1 score.
You have hard-coded column 48.

**Comment by lazyprogrammer** [comment]
We're not using the non-word frequency features since that better reflects the other concepts in the course
