### ISSUE TITLE
error

### ISSUE THREAD

**Issue by amitchandnia** [lazyprogrammer/machine_learning_examples#28]
I have installed rnn and tensorflow package but following error showing: 

from rnn_class.brown import abget_sentences_with_word2idx_limit_voc, get_sentences_with_word2idx
ModuleNotFoundError: No module named 'rnn_class'

**Comment by Elahehsrz** [comment]
Hey, I have the same question please

**Comment by vkaggal** [comment]
May I say I encountered the same as well? I am on `Python 3.7.4`.

Thank you!

**Comment by rravanales** [comment]
You need to download the complete folder 'machine_learning_examples' from lazyprogrammer, because rnn_class is a folder inside from machine_learning_examples.

**Comment by Elahehsrz** [comment]
oh thank you
