### ISSUE TITLE
Simple Question

### ISSUE THREAD

**Issue by C4A-yosy** [lazyprogrammer/machine_learning_examples#31]
Hello.

I bought "Convolutional Neural Networks in Python".
And, cnn_tf.py (Chapter 5:Sample Code in Tensorflow) is worked.

Now, I have simple question. How shold I evaluate it ???
Please give me some advice if you do not mind.

thanks!!

**Comment by yzhou2000** [comment]
not so sure

**Comment by lazyprogrammer** [comment]
Post your course-related questions on the course Q&A
