### ISSUE TITLE
Getting error while running theano2.py

### ISSUE THREAD

**Issue by pjog** [lazyprogrammer/machine_learning_examples#4]
Hi,

I am getting following error while running theano2.py in the function get_normalized_data.

FileNotFoundError: File b'../large_files/train.csv' does not exist

I cannot see the folder named large_files in the repository.

Please help!

**Comment by lazyprogrammer** [comment]
The instructions for where to get the data are described in the associated courses.

Typically there is a lecture in the introductory section called "Where to get the code and data".
