### ISSUE TITLE
Why no automated testing? Travis CI, CircleCI, AppVeyor, Azure Pipelines, etc?

### ISSUE THREAD

**Issue by cclauss** [lazyprogrammer/machine_learning_examples#47]
Lazy Programmers automate their testing. ;-)

**Comment by lazyprogrammer** [comment]
This isn't an application meant to be deployed - the name of the repository is to be taken quite literally - it is a collection of "machine learning examples".

**Comment by cclauss** [comment]
This PR said nothing about deployment.  The focus is testing -- program correctness.

**Comment by lazyprogrammer** [comment]
That wouldn't make sense in this scenario.

It would not lead to code that is appropriate for a classroom setting.

Deploying an app to the web / mobile device / backend? Makes sense.
Writing your own library? Makes sense.
Code examples to be used in the classroom? Ehh...

Show me how many repos for machine learning courses that have integrated Travis...

**Comment by cclauss** [comment]
Hogwash.  If you care about the code in this repo and you expect others to do so as well then take the time to fix up the 17 files that have Python syntax errors and also take the time to put in guardrails to ensure that such errors are automatically caught in the future.

**Comment by lazyprogrammer** [comment]
As I said: "Show me how many repos for machine learning courses that have integrated Travis..."

I don't think your definition of "syntax error" is correct, given that all the code in this repo has ben run successfully...

And if you are really passionate about this issue, wouldn't it make sense to create a Github issue under a repo owned by a university that takes in millions of dollars per year and can afford to write such tests?

Rather than a one-man operation from some guy on the Internet who you don't know that has nowhere near the vast resources compared to established academic institutions...

All you can say is "Hogwash" without actually responding to any of the points I've brought up? Not very mature...

**Comment by aadehamid** [comment]
Thank you @lazyprogrammer for all the hard work! Your repository is the only repository I have come across where I have seen the majority of these ML algorithms implemented from scratch.  Your code is crucial to my understanding of what is going on behind the hood.  I am okay with minor syntax errors here and there. You are a solid resource! THANK YOU!

**Comment by lazyprogrammer** [comment]
Thanks @aadehamid 

@cclauss Well firstly, "testing" isn't the same as "linting" but I'll play along:

While flake8 manages to print out "something" the question of whether or not that output relevant or correct is more important.

Here's a summary of what flake8 outputs:

1. Confusing Python 2 with Python 3. Obviously, print statements in Python 2 will produce syntax errors if it's assumed to be Python 3 code.

2. Spark Context - the variable is loaded automatically in the Spark REPL, it is not actually "undefined".

3. Code not being used - if you're taking a course you're going to look at the code I mentioned in the lectures. Any other code is just random stuff I played around with in the past.

As I said, the name of the repo is to be taken literally, they are "machine learning **examples**", meaning random stuff I've thrown together. WIPs, unfinished code, etc. anything can go in here. This is not "machine learning **library**", with curated reference implementations of each algorithm. (that's what SKLearn is for)

Obviously, I don't want to be notified or see warning messages if I upload something I'm working on and I already know it doesn't work. That's just a distraction and prevents a clear thought process.

The lesson here is that automated tools cannot replace thinking or following instructions in the courses.

You can't "automate away" actually paying attention and doing what you have been instructed to do.

As a current and former software engineer, obviously I understand the importance of testing and have written many tests (I even discuss "test driven development" in my lecture "how to code by yourself").

However, as I said, automation does not replace actual thinking (and this is a great example of where it leads to the **wrong** answer).

And it must be used where appropriate. I always question those who parrot things they learned at work without consideration of whether it's appropriate in different contexts (see: Serverless, Docker or MongoDB)

**Comment by cclauss** [comment]
> @cclauss Well firstly, "testing" isn't the same as "linting" but I'll play along:

1.  45 days until Python 2 end of life so let's finalize on that soon.
2. If the Spark REPL makes magic variables then just __global magic_variable__ and the linter (and humans) will understand.
3. I have no problem with dead code elimination -- That will help everyone.

I am not advocating that anyone stop thinking.  That is the opposite of what I am encouraging.  When we put guardrails on our roads, we are not encouraging drives to fall asleep at the wheel.

**Comment by lazyprogrammer** [comment]
1. This is another example of parroting without thinking. "Python 2 end of life" does not imply "the day everyone stops using Python 2".

You can read about the many businesses out there that will still continue to use Python 2 past this day.

To imply that all Python 2 code should be erased from Github is quite silly...

As I always say in my courses "learn the principles, not the syntax".

If you're so concerned with Python 2 vs. Python 3 that the differences are not just mere trivialities, then your Python skills need to be improved.

There have been many a time where I've made use of old Python 2 code and ported useful ideas in Python 3.

2. Add unnecessary code to improve the output of an unnecessary tool? Lol, sounds like new-age startup change-the-world SWE to me.

Another great example of why following instructions and paying attention to lectures is so important.

3. That doesn't make any sense. This is a collection of things I've made, *some* of which happens to be used in my courses. In what way would deleting it help anyone?

I repeat: you can't replace following instructions with automation.

I like how you turned "WIP" into "dead code" which is the exact opposite...


By the way, you still haven't answered this question:

>> As I said: "Show me how many repos for machine learning courses that have integrated Travis..."

Or this one:

>> And if you are really passionate about this issue, wouldn't it make sense to create a Github issue under a repo owned by a university that takes in millions of dollars per year and can afford to write such tests?

>> Rather than a one-man operation from some guy on the Internet who you don't know that has nowhere near the vast resources compared to established academic institutions...

I think these are rather more important than your incorrect definition of "syntax error"..

**Comment by cclauss** [comment]
You are right.  I am wrong.
