### ISSUE TITLE
Deliver requirements files 

### ISSUE THREAD

**Issue by alphacentauri12** [lazyprogrammer/machine_learning_examples#53]
Please deliver a requirement file with exact version information for your project (or a number of files for each sub project if necessary), which would really help to prevent from errors arising from different module versions.
Often problems arises just coming from a slightly different module version (older / newer) than the intended one.

**Comment by lazyprogrammer** [comment]
requirements.txt files are appropriate for projects which are meant to be deployed which is not in the spirit of this repository (e.g. you're deploying an app on Heroku). In this instance, the name is to be taken quite literally, it is a collection of "machine learning examples".

Scripts which work under different versions of the same library may appear side-by-side or in the same course.

This repository exists only for the purpose of my courses, where installing libraries is part of the student learning experience. Installing from a requirements.txt again is not conducive to that experience.
