### ISSUE TITLE
if condition in cnn_toxic.py

### ISSUE THREAD

**Issue by prateekkrjain** [lazyprogrammer/machine_learning_examples#56]
Hi,

In the code cnn_toxic.py shouldn't the the condition be "if i < num_words" instead of "if i <MAX_VOCAB_SIZE" ?

# prepare embedding matrix
print('Filling pre-trained embeddings...')
num_words = min(MAX_VOCAB_SIZE, len(word2idx) + 1)
embedding_matrix = np.zeros((num_words, EMBEDDING_DIM))
for word, i in word2idx.items():
  if i < MAX_VOCAB_SIZE:
    embedding_vector = word2vec.get(word)
    if embedding_vector is not None:
      # words not found in embedding index will be all zeros.
      embedding_matrix[i] = embedding_vector

Regards,

**Comment by lazyprogrammer** [comment]
Please use the course Q&A for course-related questions
