### ISSUE TITLE
TypeError: Bad input argument to theano function : autoencoder.py

### ISSUE THREAD

**Issue by wajihullahbaig** [lazyprogrammer/machine_learning_examples#6]
I have tried your code. But it seems there is a problem with it.
I installed theano 0.9 and tried to run the code. Training for autoencoder:1 is displayed and the code crashes with the following error

TypeError: Bad input argument to theano function with name "../autoencoder.py:43" at index 0 (0-based).  
Backtrace when that variable is created:

X_in = T.matrix('X_%s' % self.id)
TensorType(float32, matrix) cannot store a value of dtype float64 without risking loss of precision. If you do not mind this loss, you can: 1) explicitly cast your data to float32, or 2) set "allow_input_downcast=True" when calling "function". Value: "array([[ 0.51405417,  0.54865338,  0.54488875, ...,  0.46252157,
         0.44946414,  0.5688999 ],

**Comment by lazyprogrammer** [comment]
Try the suggestions in the error message
