### ISSUE TITLE
Error in linear_rl_trader.py

### ISSUE THREAD

**Issue by look4yasharth** [lazyprogrammer/machine_learning_examples#63]
There is some error in the code. Kindly check it and resolve it out as soon as possible.
My MacOS terminal says:
line 349
    with open(f'{models_folder}/scaler.pkl', 'rb') as f:
                                          ^
SyntaxError: invalid syntax

**Comment by majiang** [comment]
Did you ensure that your Python version supports
f-string?

**Comment by ShadowPeregrine** [comment]
older versions of python do not support f-strings. i would recommend upgrading python to 3.6(the one i use). hope this helps
