### ISSUE TITLE
ann_class2/tensorflow1.py - migrate from tensorflow version 1 to version 2

### ISSUE THREAD

**Issue by neoneye** [lazyprogrammer/machine_learning_examples#66]
I'm following the how to install guide of the [data-science-linear-regression-in-python](https://www.udemy.com/course/data-science-linear-regression-in-python/learn/lecture/5238010#overview) course.

The [code for verifying](https://github.com/lazyprogrammer/machine_learning_examples/blob/master/ann_class2/tensorflow1.py) that tensorflow is working correctly, didn't work for me, so I investigated how to fix it. Here is the error I was experiencing.

```
PROMPT> python3 tensorflow1.py 
Traceback (most recent call last):
  File "tensorflow1.py", line 20, in <module>
    A = tf.placeholder(tf.float32, shape=(5, 5), name='A')
AttributeError: module 'tensorflow' has no attribute 'placeholder'
```

On TF's website there is a [migration guide](https://www.tensorflow.org/guide/migrate).

Change from

    import tensorflow as tf

Change to

    import tensorflow.compat.v1 as tf
    tf.disable_v2_behavior()

This solved it for me.

**Comment by lazyprogrammer** [comment]
Please use the course Q&A for course-related questions
