### ISSUE TITLE
How to determine num_words variable when creating embedding matrix?

### ISSUE THREAD

**Issue by Nishant-Pall** [lazyprogrammer/machine_learning_examples#78]
I have been following the poetry generation notebook and at the point where we have to create an embedding matrix that uses the following code

```
# prepare embedding matrix
num_words = min(MAX_VOCAB_SIZE, len(word2idx) + 1)
embedding_matrix = np.zeros((num_words, EMBEDDING_DIM))
for word, i in word2idx.items():
    if i < MAX_VOCAB_SIZE:
        embedding_vector = word2vec.get(word)
        if embedding_vector is not None:
            # words not found in embedding index will be all zeros
            embedding_maxtrix[i] = embedding_vector
```
in the tutorial `MAX_VOCAB_SIZE = 3000` and `len(word2idx) + 1 = 4615`. Shouldn't the second line be
 `num_words = max(MAX_VOCAB_SIZE, len(word2idx) + 1)` because if we take the min, we're essentially dropping out some words from the embedding matrix? As in we should be considering each and every word in `word2idx`. What really is the point of num_words here if we can just create the embedding matrix of size `len(word2idx) + 1) * (EMBEDDING_DIM)`.

**Comment by lazyprogrammer** [comment]
Please use the course Q&A for course-related questions.
