### ISSUE TITLE
Requirements.txt file missing

### ISSUE THREAD

**Issue by imsouravstyles** [lazyprogrammer/machine_learning_examples#79]
Please add rquirement.txt file.

**Comment by lazyprogrammer** [comment]
It's not missing, this is not a library.

**Comment by ajmssc** [comment]
Your project doesn't need to be a library to have a requirements.txt file though.

**Comment by lazyprogrammer** [comment]
You missed the point of the above response (which is acceptable; it was quite short) in that it doesn't really reflect the purpose of this repository.

This repository is designed for students of my online courses (not sure if you are a student) and each course is in a folder. Different courses use different libraries, and even different courses themselves use different versions of libraries depending on when specific code was created.

This repo is not designed for say, random people who found this code and are trying to run it.

Please see here for more info: https://github.com/lazyprogrammer/machine_learning_examples/issues/55

**Comment by ajmssc** [comment]
I get what you are saying. You just use this repo to store content for your classes and you (maybe purposely) didn't organize it in a way that people can clone it and run it.

Your original answer was missing the context so I took it as a general comment without digging too much into the other issues. 
It sounds like it's not the first time people ask for this. If I were you, I would create a requirements.txt in the root and write in it a message about why you're not providing one.
