### ISSUE TITLE
CVS file error/mismatch?

### ISSUE THREAD

**Issue by rohit-kumar-j** [lazyprogrammer/machine_learning_examples#82]
Should the [linear_regression_class/moore.csv](https://github.com/lazyprogrammer/machine_learning_examples/blob/master/linear_regression_class/moore.csv) be replaced with [tf2.0/moore.csv](https://github.com/lazyprogrammer/machine_learning_examples/blob/master/tf2.0/moore.csv)? 

The [linear_regression_class/moore.py](https://github.com/lazyprogrammer/machine_learning_examples/blob/master/linear_regression_class/moore.py) file gives an error with `python 3.8.10`:

```bash
x = int(non_decmial.sub("", r[2].split("[")[0]))
IndexError: list index out of range
```
OR perhaps correcting this(Illegal quoting in line 88)?
![image](https://user-images.githubusercontent.com/37873142/188284904-2e7710ba-446c-411a-ae84-ed7619f94785.png)

**Comment by lazyprogrammer** [comment]
Thanks for your inquiry.

They are 2 separate courses.

The code for the course and the file for the course are located in their own respective folders.
